# snmpd.conf

# Listen on all interfaces on the standard SNMP UDP port
agentAddress udp:0.0.0.0:161

# Map the 'public' community string to Read-Only (RO) access for any IP
rocommunity public default

# Map the 'private' community string to Read-Write (RW) access for any IP
rwcommunity private default

# Provide some basic system information for the MIB tree
sysLocation "Virtual Docker Lab"
sysContact "admin@local.lab"
